---
Description: Launches an Apache Web Server (EC2) and a Jenkins Web Server (EC2) in Team-1's VPC on a public subnet.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
    Default: 
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID where EC2 instance(s) will be launched
    Default:  
  JenkinsKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: 
  ApacheKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: 
  JenkinsImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-
  ApacheImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-
  JenkinsInstanceType: 
    Type: String
    Default: t2.micro
  ApacheInstanceType: 
    Type: String
    Default: t2.micro
  JenkinsSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-
  ApacheSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-

Resources:
  JenkinsWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref JenkinsImageId
      InstanceType: !Sub '${JenkinsInstanceType}'
      KeyName: !Sub '${JenkinsKeyPairName}'
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref JenkinsSecurityGroupID # JenkinsServer-SG
          SubnetId: !Ref SubnetId
