---
Description: Launches an Apache Web Server (EC2) and a Jenkins Web Server (EC2) in Team-1's VPC on a public subnet.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
    Default: vpc-09c601b21fc1cdc98 # Team-1 VPC
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID where EC2 instance(s) will be launched
    Default: subnet-0d24ad74d4480002d # Team-1 Public Subnet
  JenkinsKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: Nico
  ApacheKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: apacheServer
  JenkinsImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0576380331fdddfaf
  ApacheImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-01492d9de0b3b1753
  JenkinsInstanceType: 
    Type: String
    Default: t2.micro
  ApacheInstanceType: 
    Type: String
    Default: t2.micro
  JenkinsSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0a63cdd51d2f0e44d
  ApacheSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0bf6968d322fae309

Resources:
  JenkinsWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref JenkinsImageId
      InstanceType: !Sub '${JenkinsInstanceType}'
      KeyName: !Sub '${JenkinsKeyPairName}'
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeleteOnTermination: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref JenkinsSecurityGroupID # JenkinsServer-SG
          SubnetId: !Ref SubnetId