Resources:
    CodeDeployBucket:
        Type: 'AWS::S3::Bucket'
    JenkinsRole:
      Type: 'AWS::IAM::Role'
      Properties:
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AWSCodeCommitReadOnly'
          - 'arn:aws:iam::aws:policy/AWSCodeCommitPowerUser'
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
    JenkinsInstanceProfile:
      Type: 'AWS::IAM::InstanceProfile'
      Properties:
        Path: /
        Roles:
          - !Ref JenkinsRole
    JenkinsCodeDeployRole:
      Type: 'AWS::IAM::Role'
      Properties:
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AWSCodeDeployDeployerAccess'
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS: !Join 
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref 'AWS::AccountId'
                    - ':root'
              Action:
                - 'sts:AssumeRole'
    STSAssumeRoleJenkinsCodeDeployRole:
      Type: 'AWS::IAM::Policy'
      Properties:
        PolicyName: STSAssumeRole_JenkinsCodeDeployRole
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 'sts:AssumeRole'
              Resource:
                - !GetAtt 
                  - JenkinsCodeDeployRole
                  - Arn
        Roles:
          - !Ref JenkinsRole